package uz.ruya.mobile.core.message;

import lombok.AllArgsConstructor;
import lombok.Getter;


@Getter
@AllArgsConstructor
public enum MessageKey {

    // general
    SUCCESS("success", "SUCCESS"),
    DELETED("deleted", "Успешно удалено"),
    CHANGED("changed", "Успешно изменено"),
    CODE_TIMED_OUT("code.timed.out", "Время ввода кода истекло"),
    USER_BLOCKED_CONTACT_ADMINISTRATOR("user.blocked.connect.administrator", "Пользователь блокирован. Обратитесь к администратору"),
    VERIFICATION_STATUS_NOT_CORRECT("verification.status.not.correct", "Статус верификации не корректен"),
    ECOM("ecom", "ecom"),
    ECOM_XAZNA("ecom.xazna", "ECOM Xazna"),
    PINFL("pinfl", "PINFL"),
    PASSPORT("passport", "PASSPORT"),
    FIO("fio", "F.I.O."),
    OBJECT_NOT_DELETED("object.not.deleted", "Не удалено"),
    SUCCESSFULLY_DELETED("successfully.deleted", "Успешно удалено"),
    INVALID_TOKEN("invalid.token", "Невалидный токен"),
    INVALID_AMOUNT("invalid.amount", "invalid amount"),
    ROOTED_DEVICE("rooted.device", "The device is rooted"),
    INCORRECT_PASSWORD("incorrect.password", "Некорректный пароль"),
    USER_ALREADY_EXISTS("user.already.exists", "Пользователь уже существует в базе"),
    ROLE_NOT_FOUND("role.not.found", "Роль не найдена"),
    USER_SUCCESSFULLY_REGISTERED("user.successfully.registered", "Пользователь успешно зарегистрирован"),
    VERIFICATION_TIME_EXPIRED("verification.time.expired", "Время на верификацию истекло"),

    DEVICE_BLOCKED_TIME("device.block.time", "device is blocked for %s minutes"),
    DEVICE_BLOCKED_FOREVER("device.block.forever", "device is blocked forever"),

    ACCOUNT_BLOCKED_TIME("account.block.time", "account is blocked for %s minutes"),
    ACCOUNT_BLOCKED_FOREVER("account.block.forever", "account is blocked forever"),
    TRANSACTIONS_NOT_ALLOWED("transactions.not.allowed", "Transactions not allowed for this user"),

    // auto pay
    AUTO_PAY_NOTIFICATION_DAY_REMAINING("auto.payment.notification.day.remaining", "У Вас есть запланированный платеж на сумму #AMOUNT на дату #PAYMENTDATE. Пожалуйста, проверьте остаток Вашей карты #MASKEDPAN, чтобы xazna смог правильно обработать Ваш платеж."),
    AUTO_PAY_NOTIFICATION_SUCCEED("auto.payment.notification.succeed", "Ваш запланированный платеж на сумму #AMOUNT был проведен сегодня. Спасибо что Вы пользуетесь xazna."),
    AUTO_PAY_NOTIFICATION_FAILED("auto.payment.notification.failed", "Sizning #AMOUNT so'mlik avtoto’lovingiz amalga oshirilmadi"),
    AUTO_PAY_NOTIFICATION_NOT_ENOUGH_MONEY("auto.payment.notification.not.enough.money", "К сожалению мы не смогли обработать Ваш автоплатеж на сумму #AMOUNT по причине недостаточности средств на Вашей карте #MASKEDPAN. Продолжайте пользоваться сервисом xazna и получайте кешбеки"),
    AUTO_PAY_NOTIFICATION_TITLE("auto.payment.notification.title", "Уведомление об автоплатежах"),
    AUTO_PAY_INVALID_AMOUNT("auto.payment.invalid.amount", "Auto payment invalid amount"),
    AUTO_PAY_INVALID_START_DATE("auto.payment.invalid.start.date", "Auto payment invalid start date"),
    AUTO_PAY_INVALID_END_DATE("auto.payment.invalid.end.date", "Auto payment invalid end date"),

    // application
    APPLICATION_NOT_FOUND("application.not.found", "Ariza topilmadi"),
    APPLICATION_REVIEW_SUCCESS_MESSAGE("application.review.success.message", "Arizani ko'rib chiqish uchun qabul qilindi. Jarayon tugashi bilan Sizga xabar beriladi."),
    APPLICATION_REVIEW_SUCCESS_MESSAGE_TITLE("application.review.success.message.title", "Arizani ko'rib chiqish uchun qabul qilindi. Jarayon tugashi bilan Sizga xabar beriladi."),
    APPLICATION_ALREADY_EXISTS("application.already.exists", "Sizda aktiv ariza mavjud"),
    APPLICATION_ALREADY_EXISTS_BY_OTHER_USER("application.already.exists.by.other.user", "Этот реф уже получил заявка от другого пользователя"),
    APPLICATION_ALREADY_EXISTS_TITLE("application.already.exists.title", "Sizda aktiv ariza mavjud"),

    // application keys
    KEY_1000("1000", "Ваша заявка на кредит одобрена"),
    KEY_1001("1001", "Ваша заявка принята. Проверить статус Вашей заявки можете проверить в разделе Мои заявки."),
    KEY_1002("1002", "Поздравляем Ваша пенсионная карта выдана. Для передачи Вашей карты наш коллцентр позвонит Вам. Номер вашей карты:"),
    KEY_2000("2000", "Ваша заявка на кредит не одобрена"),
    KEY_2001("2001", "У вас есть действующая заявка на пенсионную карту. Вы можете проверить статус заявки в разделе Мои заявки."),

    // card
    CARD("card", "Karta"),
    INACTIVE_CARD("inactive.card", "Неактивная карта"),
    LOCKED_CARD("locked.card", "Карта требует активации в банкомате"),
    INSUFFICIENT_CARD_BALANCE("insufficient.card.balance", "Недостаточный баланс карты"),
    CARD_EXPIRED_ERROR("card.expired.error", "Срок действия карты истек"),
    CARD_LOCK_ERROR("card.lock.error", "Ошибка блокировки карты"),
    CARD_SUCCESSFULLY_DELETED_FROM_LIST("card.successfully.deleted.from.list", "Карта успешно удалена из списка"),
    CARD_SUCCESSFULLY_UNLOCKED("card.successfully.unlocked", "Карта успешно разблокирована"),
    CARD_SUCCESSFULLY_IN_LIST("card.successfully.in.list", "Карта успешно добавлена в список"),
    CARD_SUCCESSFULLY_BLOCKED("card.successfully.blocked", "Карта успешно блокирована"),
    CARD_ALREADY_EXIST("card.already.exist", "Карта уже существует в списке ваших карт"),
    CARD_BY_UUID_NOT_FOUND("card.by.uuid.not.found", "Карта по uuid не найдена"),
    CARD_NOT_BELONG_TO_INDIVIDUAL("card.not.belong.to.individual", "Карта не принадлежит физическому лицу"),
    CARD_NOT_BELONG_TO_YOU("card.not.belong.to.you", "Карта не принадлежит физическому лицу"),
    CARD_NOT_BELONG_TO_ACCOUNT("card.not.belong.to.account", "Карта не принадлежит аккаунту"),
    CARD_NOT_FOUND_IN_PROCESSING_CHECK("card.not.found.in.processing.check", "Карта не найдена в процессинге. Проверьте корректность введенных данных"),
    CARD_NOT_FOUND_IN_PROCESSING("card.not.found.in.processing", "Карта не найдена в процессинге"),
    CARD_BLOCKED("card.blocked", "Эта банковская карта в настоящее время заблокирована."),
    CARD_BLOCKED_BY_PROCESSING("card.blocked.by.processing", "Карта заблокирована на Процессинг Центр!"),
    CARD_PAN_OR_EXPIRY_INVALID("card.pan.or.expiry.invalid", "Pan or expiry invalid, wrong format!"),
    CARD_ADD_LIMIT_EXCEED("card.add.limit.exceed", "Karta qo'shishdadi kunlik muvaffaqiyatsiz urinishlar soni tugagan"),
    CARD_IS_NOT_ACTIVE("card.is.not.active", "Эта банковская карта в настоящее время неактивна."),
    CARD_SMS_INFO_INACTIVE("card.sms.info.inactive", "Услуга смс-оповещения не подключена к данной банковской карте."),
    CARD_SMS_CONNECT_ANOTHER_PHONE("card.sms.connect.another.phone", "Эта банковская карта привязана к другому номеру телефона."),
    CARD_NOT_FOUND("card.not.found", "Карта не найдена"),
    CARD_SHOULD_NOT_BE_VIRTUAL("card.should.not.be.virtual", "Ushbu xizmat virtual kartalar uchun amal qilmaydi"),
    CARD_IS_NOT_CORRECT("card.is.not.correct", "Sms xizmatini faqat Xalq bank humo kartalari uchun yoqish mumkin"),
    CARD_ALREADY_CONNECT_SMS("card.is.already.connect.sms", "Ushbu kartada allaqachon sms xizmati mavjud"),
    CARD_SUCCESSFULLY_CONNECT_SMS("card.successfully.connect.already.connect.sms", "Ushbu karta sms xizmati muvaffaqiyatli ravishda ulandi. Xizmat aktivlashishi 15 minutdan 45 minutgacha vaqt olishi mumkin"),
    CARD_SMS_ACTIVATE_HAS_ALREADY_EXIST_APPLICATION("card.sms.activate.has.already.exist.application", "Sizda aktiv ariza mavjud,keyinroq urinib ko'ring"),
    CARD_SMS_ACTIVATE("card.sms.activate", "Sms xabarnoma"),
    CARD_NOT_FOUND_IN_PROCESSING_RECIPIENT("card.not.found.in.processing.recipient", "Карта в процессинге не найдена: Получатель"),
    CARDUUID_CAN_NOT_BE_NULL("carduuid.can.not.be.null", "cardUUID can not be null"),
    CARD_INFO_GET_ERROR("card.info.get.error", "card.info.get.error"),
    CARD_GET_MASKED_PAN_ERROR("card.get.masked.pan.error", "Ошибка получения маск карты"),
    CARD_NOT_FOUND_WITH_THIS_GIVEN_UUID("card.not.found.with.this.given.uuid", "card not found with this given uuid"),
    CARD_BY_ID_NOT_FOUND_SENDER("card.by.ID.not.found.sender", "Карта по id не найдена: Отправитель"),
    CARD_NOT_FOUND_BY_UUID_SENDER("card.not.found.by.uuid.sender", "Карта по uuid не найдена : Отправитель"),
    CARD_NOT_FOUND_BY_UUID_RECIPIENT("card.not.found.by.uuid.recipient", "Карта по uuid не найдена : Получатель"),
    CARD_IN_BLOCK_LIST("card.in.block.list", "Unable to transfer. Please contact support service"),
    SENDER_CARD_NOT_FOUND("sender.card.not.found", "Карта не найдена: Отправитель"),
    RECIPIENT_CARD_NOT_FOUND("recipient.card.not.found", "Карта не найдена: Получатель"),
    RECIPIENT_CARD_NOT_ACTIVE("recipient.card.not.active", "Карта получателя не активна"),
    RECIPIENT_NOT_SELECTED("recipient.not.selected", "Qabul qiluvchi tanlanmagan"),
    ACTIVE_CARD_NOT_FOUND("active.card.not.found", "Aktiv karta topilmadi"),
    CARD_STATUS_MUST_BE_ACTIVE("card.status.must.be.active", "Hurmatli mijoz, ayni damda kartangiz faol holatda emas. Iltimos kartangizni faollashtiring"),
    VIRTUAL_CARD_CANNOT_ACCEPTED("virtual.card.cannot.accepted", "Ushbu amaliyot virtual karta turida faol emas"),
    CARD_SUCCESSFULLY_DEACTIVATED("card.successfully.deactivated", "Karta no faol holatga o'zgartirildi"),
    CARD_ALREADY_DEACTIVATED("card.already.deactivated", "Karta allaqachon no faol holatga o'tkazilgan"),
    CARD_ASSIGN_PIN_REQUEST_ACCEPTED("card.assign.pin.request.accepted", "Karta pin kodini o'zgartirish uchun so'rovingiz qabul qilindi, javob xabarnoma tarzda 2 daqiqa ichida yuboriladi"),
    CARD_ADD_VERIFICATION_CODE_INCORRECT("card.add.verification.code.incorrect", "The verification code is incorrect"),
    CARD_ADD_CONFIRM_CODE_EXPIRED("card.add.confirm.code.expired", "You have not been sent a code or the code has expired"),
    CARD_ADD_CONFIRM_CODE_ENTERED_THREE_TIMES("card.add.confirm.code.entered.three.times", "The code has been entered incorrectly 3 times. Please try again after 24 hours!"),
    CARD_CONFIRMATION_CODE_ALREADY_SENT("card.add.confirmation.code.already.sent", "OTP code has already been sent"),

    // wallet
    WALLET_NOT_FOUND("wallet.not.found", "Кошелек не найден"),
    REGULAR_WALLET_NOT_FOUND("regular.wallet.not.found", "Regular wallet not found"),
    WALLET_BLOCKED("wallet.blocked", "Кошелек блокирован"),
    WALLET_PUSH_TITLE("wallet.push.title", "Wallet uchun ariza berildi"),
    WALLET_ALREADY_CREATED("wallet.already.created", "Wallet already created"),
    WALLET_CREATED("wallet.created", "Wallet created"),
    WALLET_ALREADY_EXIST("wallet.already.exist", "wallet already exist"),
    WALLET_PROCESSING_IS_TEMPORARILY_UNAVAILABLE("wallet.processing.is.temporarily.unavailable", "Процессинг кошельков временно недоступен"),
    THE_BALANCE_ON_BLOCKED_WALLET_IS_NOT_PROVIDED("the.balance.on.blocked.wallet.is.not.provided", "Баланс по блокированному кошельку не предоставляется"),
    INSUFFICIENT_WALLET_BALANCE("insufficient.wallet.balance", "Недостаточный баланс кошелька"),
    USER_WALLET_HAS_BLOCKED_ERROR("user.wallet.has.blocked.error", "Hurmatli mijoz, Sizga kredit ajratishda elektron kasheloklar bilan texnik muammo mavjud. Qo'shimcha ma'lumot olish uchun ilovaning onlayn chat xizmatiga yoki 1106 qisqa raqamiga murojaat qilishingiz mumkin."),
    USER_WALLET_NOT_FOUND("user.wallet.not.found", "Hurmatli mijoz, Sizga kredit ajratishda elektron kasheloklar bilan texnik muammo mavjud. Qo'shimcha ma'lumot olish uchun ilovaning onlayn chat xizmatiga yoki 1106 qisqa raqamiga murojaat qilishingiz mumkin."),
    INFORMATION_NOT_FOUND_ECOM("information.not.found.ecom", "Tashqi tizimda ma'lumotlar topilmadi"),
    INVOICE_ALREADY_PAYED("already.payed", "Invoice already payed"),
    INVOICE_EXPIRE("invoice.expire", "Invoice expired"),

    // loan
    LOAN("loan", "loan"),
    LOAN_REPAYMENT("loan.repayment", "Кредит погашение"),
    LOAN_NOT_FOUND("loan.not.found", "Кредитный продукт не найден"),
    LOAN_PRODUCT_IS_NOT_ACTIVE("loan.product.is.not.active", "Кредитный продукт не активен"),
    CANNOT_CHOOSE_PRODUCT("cannot.choose.product", "Hurmatli mijoz, Siz ish haqi loyihasi  yoki byudjet tashkiloti xodimi emassiz. Hozirda Sizga onlayn kredit ajrata olmaymiz. Qo’shimcha ma’lumot olish uchun, ilovaning onlayn chat xizmatiga yoki 1106 qisqa raqamiga murojaat qilishingiz mumkin."),
    CHOOSE_ANOTHER_PRODUCT("choose.another.product", "Hurmatli mijoz, Siz byudjet tashkiloti xodimi emassiz. Qo’shimcha ma’lumot olish uchun, ilovaning onlayn chat xizmatiga yoki 1106 qisqa raqamiga murojaat qilishingiz mumkin."),
    CHOOSE_UZASBO_PRODUCT("choose.uzasbo.product", "Hurmatli mijoz, Siz ish haqi loyihasi ishtirokchisi emassiz. Qo’shimcha ma’lumot olish uchun, ilovaning onlayn chat xizmatiga yoki 1106 qisqa raqamiga murojaat qilishingiz mumkin."),
    TECHNICAL_BREAK("technical.break", "Технический перерыв"),
    PLEASE_WAIT("please.wait", "Hurmatli mijoz, Iltimos jarayon yakunlanishini kuting."),
    YOUR_DOCUMENT_UPDATING_PLEASE_WAIT("your.document.updating.please.wait", "Hurmatli mijoz, Sizning ma'lumotlaringiz yaniglashga berildi. Iltimos jarayon yakunlanishini kuting."),
    LOAN_PUSH_TITLE("loan.push.title", "Kredit uchun ariza"),
    CANCEL_APPLICATION_STATUS_ERROR("cancel.application.status.error", "Hurmatli mijoz, Sizning arizangiz holatida xatolik"),
    WAITING_APPLICATION_MESSSAGE("waiting.application.message", "Firibgarlikni oldini olish maqsadida #TIME soat mobatnida aloqa markazi 1106 bilan bog'lanib shaxsingizni tasdiqlashigiz zarur!"),
    WAITING_APPLICATION_TIME("waiting.application.time", "Qisqa muddat qoldi"),
    WAITING_APPLICATION_TIME_FULL("waiting.application.time.full", "#TIME qoldi"),

    SUCCESS_LOAN_PAYMENT_TO_WALLET("success.loan.payment.to.wallet", "Hurmatli mijoz, Sizning kredit olishga arizangiz muvaffaqiyatli qabul qilindi va #AMOUNT UZS miqdorida pul mablag'i elektron hamyoningizga o'tkazib berildi."),
    SUCCESS_LOAN_PAYMENT_TO_SPONSOR("success.loan.payment.to.sponsor", "Hurmatli mijoz, Sizning kafillik bo'yicha talabaning kredit arizasi muvaffaqiyatli qabul qilindi va #AMOUNT UZS miqdorida pul mablag'i talaba muassasa hisob raqamiga o'tkazib berildi."),
    SUCCESS_LOAN_PAYMENT_TO_STUDENT("success.loan.payment.to.student", "Hurmatli mijoz, Sizning kredit olishga arizangiz muvaffaqiyatli qabul qilindi va #AMOUNT UZS miqdorida pul mablag'i o'quv muassasangiz hisob raqamiga o'tkazib berildi."),
    SUCCESS_LOAN_PAYMENT_TO_VIRTUAL_CARD("success.loan.payment.to.virtual.card", "Hurmatli mijoz, Sizning kredit olishga arizangiz muvaffaqiyatli qabul qilindi va #AMOUNT UZS miqdorida pul mablag'i virtual kartangizga o'tkazib berildi."),
    SUCCESS_LOAN_PAYMENT_TO_WALLET_TITLE("success.loan.payment.to.wallet.title", "Sizga onlayn kredit ajratilindi."),
    SUCCESS_LOAN_PAYMENT_TO_SPONSOR_TITLE("success.loan.payment.to.sponsor.title", "Talabaga onlayn kredit ajratilindi."),
    SUCCESS_LOAN_PAYMENT_TO_VIRTUAL_CARD_TITLE("success.loan.payment.to.virtual.card.title", "Sizga onlayn kredit ajratilindi."),
    PROCESS_LOAN_TO_ISSUANCE("process.loan.to.process", "Hurmatli mijoz, Sizning arizangiz jarayonda bo'lganligi sabali bekor qila olmaysiz"),
    LOAN_CANCEL_PUSH("loan.cancel60.push", "Уважаемый клиент, Ваша заявка на получение кредита #ORDERID была отменена. Мы хотели бы сообщить вам, что срок подачи заявок истек. Мы просим вас повторно подать заявку на кредит. Для получения дополнительной информации вы можете обратиться в службу онлайн-чата приложения или по короткому номеру 1106."),
    LOAN_CANCEL_PUSH_WITHOUT_ORDER("loan.cancel.push.without.order", "Hurmatli mijoz, Sizning kredit arizangiz bekor qilindi. Arizani davom ettirishga belgilangan vaqt tugagani ma'lum qilamiz. Kredit olish uchun ilovadan qayta murojaat qilishingizni so'raymiz. Qo'shimcha ma'lumot olish uchun ilovaning onlayn chat xizmatiga yoki 1106 qisqa raqamiga murojaat qilishingiz mumkin."),
    LOAN_CANCEL_PUSH_MY_ID("loan.cancel.push.my.id", "Hurmatli mijoz, Sizning kredit arizangiz tasdiqlash jarayonidagi urinishlar sababli bekor qilindi. Kredit olish uchun ilovadan qayta murojaat qilishingizni so'raymiz. Qo'shimcha ma'lumot olish uchun ilovaning onlayn chat xizmatiga yoki 1106 qisqa raqamiga murojaat qilishingiz mumkin."),

    SUCCESS_OMUC_NOT_FOUND("success.omuc.not.found", "Успешный сертификат не найден"),

    SELF_EMPLOYMENT_NOT_FOUND("self.employment.not.found", "Sertifikat topilmadi"),
    SELF_EMPLOYMENT_EXPIRE("self.employment.expired", "sertifikat muddat ...."),
    SELF_EMPLOYMENT_NOT_ENOUGH_MONEY("self.employment.not.enough.money", "Sizga #MONEY sum  miqdori yetarli emas"),
    SELF_EMPLOYMENT_WAY("self.employment.way", "Yo'nalishingiz kredi olish uchun huquqi yo'q"),
    SELF_EMPLOYMENT_EXPIRE_WITH_TIME("self.employment.expired.with.time", "Hurmatli mijoz, Bu mahsulot bo'yicha #day kundan so'ng ariza bersangiz bo'ladi"),

    EDU_DATA_NOT_FOUND("edu.data.not.found", "Hurmatli mijoz, Talim kredit platformasidan arizalar kelmagani sababli sizning malumotingiz topilmadi"),
    EDU_APPLICATION_NOT_FOUND("edu.application.not.found", "Hurmatli mijoz, Talim kredit platformasidan arizangiz topilmadi"),
    EDU_APPLICATION_CONTRACT_FOUND("edu.application.contract.not.found", "Hurmatli mijoz, Bu o'quv yili uchun ta'lim muassasasi bilan shartnoma topilmadi"),
    EDU_SPONSOR_CONFIRM_CONVEYOR("edu.sponsor.confirm.conveyor", "Kafilga xabar yuborildi. Kafil #TIME daqiqa mobaynida xazna ilovasidan ro'yxatga o'tib shaxsga doir malumotlardan foydalanishga rozilik bildirishi zarur"),
    EDU_CONFIRMATION_APPLICATION_NAME("edu.confirmation.application.name", "Kafillikni tashdiqlash"),
    EDU_SPONSOR_CONFIRM_TITLE("edu.sponsor.confirm.title", "Kafil roziligi"),
    EDU_SPONSOR_CONFIRM_BODY("edu.sponsor.confirm.body", "<p>Talaba #STUDENT nomiga rasmiylashtirilayotgan Talaba kreditiga kafil sifatida <a href = 'https://lex.uz/uz/docs/6163025/'>qonun talablari</a> doirasida shaxsga doir malumotlaringizdan foydalanishga rozilik bildirasizmi?</p>"),
    EDU_SPONSOR_CONFIRM_SHORT_BODY("edu.sponsor.confirm.short.body", "Talaba #STUDENT nomiga rasmiylashtirilayotgan Talaba kreditiga kafil sifatida qonun talablari doirasida shaxsga doir malumotlaringizdan foydalanishga rozilik bildirasizmi?"),
    EDU_CANNOT_ADD_SPONSOR("edu.cannot.add.sponsor", "Hozirda kafil qo'sha olmaysiz. Ta'lim kredit platformasidan qayta qo'shganingizdan so'ng, qayta azira qoldirsangiz bo'ladi"),
    EDU_CANNOT_ADD_ISSUED_SPONSOR("edu.cannot.add.issued.sponsor", "Hurmatli mijoz, Siz kiritayotgan mijoz avval kafil  bo'lganligi sababli kirita olmaysiz, Iltimos boshqa kafil biriktirsangiz"),
    EDU_CANNOT_ADD_YOURSELF("edu.cannot.add.yourself", "Kafillikka o'zingizni qo'sha olmaysiz. Iltimos boshqa ma'lumot kiritsangiz"),
    EDU_CANNOT_AGREE_SPONSOR_FAIL("edu.cannot.agree.sponsor", "Talaba azizasi rad etilganligi sababli kafillika rozilik bildira olmaysiz"),
    EDU_CANNOT_AGREE_SPONSOR_SUCCESS("edu.cannot.agree.sponsor.success", "Talaba arizasiga boshqa kafil bo'ldi"),
    EDU_CANNOT_AGREE_NOW("edu.cannot.agree.now", "Kafillik roziligining muddati tugaganligi tufayli ushbu amaliyotni bajara olmaysiz"),
    EDU_SUCCESS_AGREED("edu.success.agreed", "Arizani ko'rib chiqish uchun qabul qilindi. Jarayon tugashi bilan Sizga xabar beriladi"),
    EDU_SUCCESS_PUSH("edu.success.push", "Tabriklaymiz! #ORDERID kredit arizangiz ma'qullandi. Iltimos, ma’qullangan kredit miqdorini 'Mening bankim' ('Kreditlar' - 'Mening' bo'limiga) o'tgan holda 1 soat ichida tasdiqlashingizni so'raymiz. Ajratilingan kredit Oliy talim shartnomasiga o'tkazib beriladi."),
    EDU_NOT_AGREE("edu.not.agree", "Kafil rozilik bildirmadi. Boshqa kafil biriktiring"),
    EDU_NOT_CONFIRM("edu.not.confirm", "Kafil shaxsga doir malumotlarini foydalanishni tasdiqlamadi. Boshqa kafil biriktiring"),
    EDU_SPONSOR_NEW("edu.sponsor.new", "Kafil shaxsga doir ma'lumotlarni foydalanishga rozilik bildirishi zarur"),
    EDU_SPONSOR_PROCESS("edu.sponsor.process", "Kafil ma'lumotlari qayta ishlanmoqda"),
    EDU_SPONSOR_FAIL("edu.sponsor.fail", "Bankning kredit talablariga mos kelmaganligi uchun ushbu kafil rad qilindi. Iltimos boshqa kafil biriktiring!"),
    EDU_SPONSOR_SUCCESS("edu.sponsor.success", "Tabriklaymiz! Sizga kredit maqullandi. Mablag'ni 1 soat vaqt davomida tasdiqlashingizni so'raymiz"),
    EDU_SPONSOR_SUCCESS_STUDENT_PROCESS("edu.sponsor.success.student.sponsor", "Kafil tasdiqlash jarayonida. Kafil 'Mening bankim' ('Kreditlar' - 'Mening' bo'limiga) o'tgan holda Kafillik arizasini tasdiqlashi zarur"),
    EDU_SPONSOR_NOT_AGREE("edu.sponsor.not.agree", "Talaba kafilligingiz bekor qilindi"),
    NOT_FOUND_STUDENT("not.found.student", "Talabalar ro'yxatidan topilmadingiz"),
    EDU_SPONSOR_NOT_FOUND("edu.sponsor.not.found", "Kafil xazna platformasidan ro'yhatdan o'tgan bo'lishi kerak"),
    EDU_PRODUCT_PERIOD("edu.sponsor.period", "o'quv yili"),
    EDU_NO_DAVLAT_SERVICE_TEMPORARILY_UNAVAILABLE("edu.no.davlat.service.temporarily.unavailable", "Сервис временно не доступно"),
    EDU_DAVLAT_SERVICE_TEMPORARILY_UNAVAILABLE("edu.davlat.service.temporarily.unavailable", "Сервис временно не доступно"),
    EDU_SPONSOR_SOCIAL_PROTECTION("edu.social.protection", "Hurmatli mijoz, Vaqtinchalik ijtimoiy himoya reystriga kiritilgan mijozlarga xizmat ko'rsatish faol emas."),
    EDU_CREDIT_AMOUNT_CHECK("edu.student.amount.check", "Hurmatli mijoz, Ta'lim kredit platformasidan kiritgan summangiz #AMOUNT_MAX dan kichik yoki #AMOUNT_MIN dan yuqori bo'lishi kerak. Iltimos platformadan qayta ariza topshirganingizdan so'ng murojaat qilishingiz mumkin."),
    EDU_PERIOD_EMPTY("edu.period.empty", "Hurmatli mijoz, Ta'lim muassasangizdan o'quv davri kelmaganligi sababli arizangiz qabul qilinmadi."),

    RETRY("please.retry", "Iltimos qayta urinib ko'rsangiz."),

    CRITICAL_MORE("critical.more.button", "Batafsil"),
    CRITICAL_CONFIRM("critical.confirm.button", "Tashdiqlash"),
    CRITICAL_PERMIT("critical.permit.button", "Rasmiylashtirish"),

    // deposit
    DEPOSIT_DECREASE_INVALID_AMOUNT("deposit.decrease.invalid.amount", "Deposit decrease invalid amount"),
    CHECK_OPEN_DEPOSIT_ERROR("check.open.deposit.error", "Ошибка открытия депозита"),
    CHECK_INCREASE_DEPOSIT_ERROR("check.increase.deposit.error", "Ошибка пополнения депозита"),
    PAYMENT_DEPOSIT_ABS_ERROR("payment.deposit.abs.error", "Ошибка соединения с системой"),
    PAYMENT_DEPOSIT_ABS_METHOD_ERROR("payment.deposit.abs.method.error", "Системой вернул ошибку"),
    INVALID_DEPOSIT_AMOUNT("invalid.deposit.amount", "Неправильная сумма"),
    WRONG_DEPOSIT("wrong.deposit", "Неправильный депозит"),
    INVALID_DEPOSIT_CLOSE_DAY("invalid.deposit.close.day", "Неправильная дата закрытия депозита"),
    OPEN_DEPOSIT_SUCCESS("open.deposit.success", "Открытия онлайн-депозита успешно выполнена!"),
    DEPOSIT_IS_NOT_ACTIVE("deposit.is.not.active", "Депозит не активна!"),
    CLOSE_DEPOSIT_SUCCESS("close.deposit.success", "Закрытия онлайн-депозита успешно выполнена!"),
    OPEN_DEPOSIT_OWNER_NAME("open.deposit.owner.name", "Открытие онлайн-депозита "),
    INVESTING_DEPOSIT_OWNER_NAME("investing.deposit.owner.name", "Пополнение онлайн-депозита "),
    WITHDRAWAL_DEPOSIT_TO_WALLET("investing.deposit.owner.name", "Зачисление процентов на кошелек "),
    DECREASE_DEPOSIT_TO_WALLET("decrease.deposit.wallet", "Зачисление на кошелек "),
    CLOSE_DEPOSIT_OWNER_NAME("investing.deposit.owner.name", "Закрытия онлайн-депозита "),
    DEPOSIT_REQUEST_ACCEPTED("deposit.request.accepted", "Sizning omonat ochish uchun arizangiz qabul qilindi!"),
    DEPOSIT_DECREASE_MIN_AMOUNT("deposit.decrease.min.amount", "Amount should be at least #AMOUNT sum"),
    DEPOSIT_DECREASE_EXISTING_AMOUNT("deposit.decrease.existing.amount", "Sizda #AMOUNT so'm miqdoridagi omonat foizlari mavjud. Ushbu foiz miqdori ham hamyoningizga o'tkaziladi"),

    // operation
    OPERATION_ERROR("operation.error", "Ошибка операции"),
    OPERATION_SUBMITTED_FOR_PROCESSING("operation.submitted.for.processing", "Операция передана на обработку"),
    OPERATION_NOT_SUPPORTED("operation.not.supported", "Операция не поддерживается"),
    OPERATION_NOT_FOUND("operation.not.found", "Операция не найдена"),
    OPERATION_NOT_AVAILABLE("operation.not.available", "Операция не доступна"),
    OPERATION_PENDING_PROCESSING("operation.pending.processing", "Операция не доступна"),
    OPERATION_PENDING("operation.pending", "Операция ожидает обработки"),
    OPERATION_PROHIBITED("operation.prohibited", "Операция запрещена"),
    DATA_SUBMITTED_FOR_PROCESSING("data.submitted.for.processing", "Данные переданы на обработку"),
    TIYIN_AMOUNT_NOT_SUPPORTED("tiyin.amount.not.supported", "Сумма с тийном не поддерживается"),
    RECIPIENT_CARD_LIMIT_EXCEEDED("recipient.card.limit.exceeded", "Вы не можете осуществить перевод, так как превышена ежедневная сумма денег, поступающая на карту получателя."),
    INVALID_TERMINAL_FOR_RECIPIENT_CARD("invalid.terminal.for.recipient.card", "Невозможно провести операцию по карте получателя."),
    USER_IN_BLACKLIST("user.in.blacklist", "Foydalanuvchi qora ro'yxatda"),

    // service
    SERVICE_ERROR("service.error", "Ошибка сервиса"),
    SERVICE_PROCESSING_ERROR("service.processing.error", "Ошибка обработки сервиса"),
    SERVICE_NOT_FOUND("service.not.found", "Сервис не найден"),
    SERVICE_NOT_ACTIVE("service.not.active", "Сервис неактивен"),
    SERVICE_TEMPORARILY_UNAVAILABLE("service.temporarily.unavailable", "Сервис временно не доступно"),
    PAYMENT_SERVICE_NOT_FOUND("payment.service.not.found", "Сервис для оплаты не найден"),
    SERVICE_HAS_TECHNICAL_WORKS("service.has.technical.works", "В сервисе проводиться технические работы"),
    SERVICE_ID_NOT_ENTERED("service.ID.not.entered", "Не введен ID услуги"),
    SERVICE_CAN_NOT_BE_NULL("service.can.not.be.null", "service can not be null"),
    SERVICE_CANNOT_BE_NULL("service.cannot.be.null", "Служба не может быть нулевой"),
    TO_USE_THE_SERVICE_YOU_MUST_PASS_THE_IDENTIFICATION("to.use.the.service.you.must.pass.the.identification", "Для пользования услугой необходимо пройти Идентификацию"),

    // my home
    MY_HOME_BALANCE_ALERT_AMOUNT_INVALID("my.home.balance.alert.amount.invalid", "Для этого платежного сервиса вы не можете добавить сумму оповещения."),
    MY_HOME_BALANCE_ALERT_EXISTS("my.home.balance.alert.exists", "Сумма оповещения уже существует."),
    MY_HOME_BALANCE_ALERT_NOTIFICATION_TITLE("my.home.balance.alert.notification.title", "Оповещение о моем домашнем сервисе."),
    MY_HOME_BALANCE_ALERT_NOTIFICATION_BODY("my.home.balance.alert.notification.body", "Sizning \"MENING UYIM\" sahifasidagi #NAME uyingizning #TITLE xizmatining #MAINFIELD hisob raqamingizda #BALANCE so'm mablaq qoldi"),
    MY_HOME_BALANCE_ALERT_ERROR("my.home.balance.alert.error", "Ushbu servisni qo'shib bo'lmaydi"),

    // invalid
    INVALID_REQUEST("invalid.request", "Неверный запрос"),
    INVALID_CODE_FILIAL("invalid.mfo", "Неверный код филиала"),
    INVALID_CARD_TYPE("invalid.card.type", "Неверный тип карты"),
    INVALID_ACCOUNT_NUMBER("invalid.account.number", "Неверный номер счета"),
    INVALID_RECIPIENT_NAME("invalid.recipient.name", "Имя получателя должно содержать более 3 символов"),

    // unknown
    UNKNOWN_ERROR("unknown.error", "Неизвестная ошибка"),
    UNKNOWN_ID("unknown.ID", "Неизвестный идентификатор"),
    UNKNOWN_CARD_TYPE("unknown.card.type", "Неизвестный тип карты"),
    UNKNOWN_OPERATION_TYPE("unknown.operation.type", "Неизвестный тип операции"),

    // cannot be null (required)
    START_DATE_CANNOT_BE_NULL("start.date.cannot.be.null", "startDate can not be null"),
    END_DATE_CANNOT_BE_NULL("end.date.cannot.be.null", "endDate can not be null"),
    NAME_CANNOT_BE_NULL("name.cannot.be.null", "Имя не может быть пустым"),
    AMOUNT_CANNOT_BE_NULL("amount.cannot.be.null", "amount can not be null"),
    CARD_CANNOT_BE_NULL("card.cannot.be.null", "Карта не может быть пустой"),
    AUTO_PAY_CANNOT_BE_NULL("auto.pay.cannot.be.null", "Автоплатеж не может быть пустым"),
    UUID_CANNOT_BE_NULL("uuid.cannot.be.null", "UUID can not be null"),
    UUID_CAN_NOT_BE_NULL("uuid.can.not.be.null", "uuid can not be null"),
    START_DATE_CAN_NOT_BE_NULL("start.date.can.not.be.null", "startDate can not be null"),
    DOC_SERIES_CAN_NOT_BE_NULL("doc.series.can.not.be.null", "Doc series cn not be null"),
    DOC_NUMBER_CAN_NOT_BE_NULL("doc.number.can.not.be.null", "Doc number cn not be null"),
    IMT_AMOUNT_ERROR("imt.amount.error", "amount should in range #minAmount and #maxAmount"),
    IMT_AMOUNT_NOT_EQUAL("imt.amount.not.equal", "imt amount not equal"),

    // not found
    ENTITY_NOT_FOUND("entity.not.found", "entity not found"),
    ENTITY_NOT_FOUND_WITH_ID("entity.not.found.with.ID", "Entity Not Found withId: "),
    ENTITY_NOT_FOUND_WITH_GIVEN("entity.not.found.given", "Entity not found with given filter"),
    CATEGORY_NOT_FOUND("category.not.found", "Категория не найдена"),
    ADDRESS_NOT_FOUND("address.not.found", "Manzil topilmadi"),
    NOTIFICATION_NOT_FOUND("notification.not.found", "Уведомление не найдено"),
    DATA_NOT_FOUND("data.not.found", "Данные не найдены"),
    DOCUMENT_NOT_FOUND("document.not.found", "Document not found"),
    PROCESSING_NOT_FOUND("processing.not.found", "Processing #OPERATIONTYPENAME not found!"),
    AUTO_PAYMENT_NOT_FOUND("auto.payment.not.found", "Актуальный баланс"),
    BUSINESS_FIELDS_NOT_FOUND("business.fields.not.found", "Business fields not found"),

    REDEMPTION_INFO_ERROR("redemption.info.error", "Redemption info error"),
    REDEMPTION_INFO_IS_NOT_WORKING("redemption.info.is.not.working", "Redemption info is not working!"),
    REDEMPTION_PAYMENT_IS_NOT_WORKING("redemption.payment.is.not.working", "Redemption payment is not working!"),

    INFO_ERROR("info.error", "info error"),

    PAYMENT_ERROR("payment.error", "payment error"),
    PAY_DATE_EXPIRED("pay.date.expired", "Срок выплаты истек"),
    PAYMENT_ALREADY_COVERED("payment.already.covered", "Siz ushbu xizmatdan oldin foydalangansiz. Imtixon xarajatlari qoplab berilgan. Qo'shimcha ma'lumot olish uchun 1106 raqamiga yoki ilova chat xizmatiga murojaat qilishingizni so'raymiz."),
    PAYMENT_DATE_NOT_CONFIRMED("payment.date.not.confirmed", "Дата платежа не подтверждена"),
    PAYMENT_AMOUNT_IS_EMPTY("payment.amount.is.empty", "Сумма платежа пуста"),

    NO_REDEMPTIONS_FOUND_FOR_THIS_PERIOD("no.redemptions.found.for.this.period", "Погашения за этот период не найдены"),

    ONLY_FOR_XALQ_BANK_CARDS("only.for.Xalq.bank.cards", "Функция доступна для карт XalqBanki"),
    CARD_BLOCK_UNBLOCK_NOT_AVAILABLE("card.block.unblock.not.available", "Функция не доступна для карт"),

    TRANSACTION_COMPLETED_SUCCESSFULLY("transaction.completed.successfully", "Транзакция успешно выполнена"),
    YOU_CAN_APPLICATION_VIEW("you.can.view.application.message", "Вы можете увидеть результат транзакции в отделе заявок"),
    TRANSACTION_MUST_BE_CONFIRMED("transaction.must.be.confirmed", "Транзакция должна быть подтверждена"),
    INVALID_CODE_ENTERED_TRY_AGAIN("invalid.code.entered.try.again", "Транзакция должна быть подтверждена"),
    CONFIRMATION_CODE_INPUT_LIMIT_EXCEEDED("confirmation.code.input.limit.exceeded", "Превышен лимит ввода кода подтверждения"),
    PENDING_OPERATION_EXISTS("pending.operation.exists", "У вас есть активная транзакция, подождите"),

    SUYUNCHI_ACTIVE_INFO_EXISTS("suyunchi.service.error", "Ijtimoiy himoya milliy agetligida kutilmagan xatolik"),
    SUYUNCHI_SERVICE_ERROR("suyunchi.service.error", "Ijtimoiy himoya milliy agetligida kutilmagan xatolik"),
    SUYUNCHI_INFO_NOT_FOUND("suyunchi.info.not.found", "Ma'lumot topilmadi"),
    SUYUNCHI_IHMA_NOT_FOUND("suyunchi.ihma.not.found", "Ma'lumot topilmadi"),
    SUYUNCHI_ALREADY_PAYED_IN_BRANCH("suyunchi.already.payed.in.branch", "Suyunchi puli avval qoplab berilgan"),
    SUYUNCHI_ALREADY_PAYED_IN_XAZNA("suyunchi.already.payed.in.xazna", "Suyunchi puli avval qoplab berilgan"),
    SUYUNCHI_ALREADY_ASSIGNED_IN_BRANCH("suyunchi.already.assigned.in.branch", "Suyunchi puli avval qoplab berilgan"),
    SUYUNCHI_ALREADY_ASSIGNED_IN_XAZNA("suyunchi.already.assigned.in.xazna", "Suyunchi puli avval qoplab berilgan"),
    SUYUNCHI_RECEIPT("suyunchi.receipt", "Suyunchi pulini qoplash"),

    FUNERAL_RECEIPT("funeral.receipt", "Dafn pulini qoplash"),
    FUNERAL_RECIPIENT_HAS_NOT_RELATION("funeral.recipient.has.not.relation", "Qabul qiluvchi shaxs bian vafot etgan shaxsning qarindoshligi aniqlanmandi"),
    FUNERAL_INFO_NOT_FOUND("funeral.info.not.found", "Ma'lumot topilmadi"),
    FUNERAL_SERVICE_ERROR("funeral.service.error", "Ijtimoiy himoya milliy agetligida kutilmagan xatolik"),

    INTERNATIONAL_EXAM_INFORMATION_NOT_FOUND("international.exam.information.not.found", "Sizning so'rovingiz bo'yicha hech qanday ma'lumot topilmadi. Qo'shimcha ma'lumot olish uchun 1106 raqamiga yoki ilova chat xizmatiga murojaat qilishingizni so'raymiz."),
    INTERNATIONAL_EXAM_PAY_DATE_NOT_CONFIRMED("international.exam.pay.date.not.confirmed", "Yoshlar ishlari agentligi tomonidan tasdiqnoma berilgan sanadan 12 (kalendar) kun  o'tgandan so'ng  mablag' to'lab beriladi!"),
    INFORMATION_NOT_FOUND_FOR_STUDENT("information.not.found.for.student", "Информация не найдена. Уважаемый клиент, просим Вас обращаетесь с высшим учебным заведением."),
    INFORMATION_NOT_FOUND_FOR_CHILD("information.not.found.for.child", "Информация не найдена. Уважаемый клиент, просим Вас обращаться в дошкольное образовательное учреждение."),
    INTERNATIONAL_EXAM_RECEIPT("international.exam.receipt", "Возмещение расходов на экзамены в рамках международных экзаменационных систем"),
    INPS_OUTCOME_RECEIPT("inps.outcome.receipt", "JBPT (NPS) mablag'larini olish"),
    INFO_NOT_FOUND("info.not.found", "Ma'lumot topilmadi"),
    GET_INTERNATIONAL_TRANSFER_INVALID_USER("get.international.transfer.invalid.user", "Вы не являетесь именным владельцем реф номер"),
    AGREEMENT_MESSAGE_CREDIT_MIT_MONEY_TO_USD_WALLET("agreement.message.credit.money.to.usd.wallet", "Вы согласны перевести свои деньги на usd кошелек ?!"),

    TRANSFER_TO_CORPORATE_CARD_IS_PROHIBITED("transfer.to.corporate.card.is.prohibited", "Перевод на корпоративную карту запрещена"),

    ERROR_IN_UNLOCKING_CARD("error.in.unlocking.card", "Ошибка при разблокировке карты"),

    ERROR_IN_BLOCKING_CARD("error.in.blocking.card", "Ошибка блокировки карты"),
    ERROR_CREATING_CUSTOMER("error.creating.customer", "Ошибка при создании клиента"),

    DATA_DECODING_ERROR("data.decoding.error", "Ошибка декодирования данных"),

    ERROR_GETTING_BALANCE("error.getting.balance", "Ошибка в получении баланса"),

    INSURANCE_PAYMENT_POLICY("insurance.payment.policy", "Оплата страховки (Полис)"),
    INSURANCE_ERROR("insurance.error", "Оплата страховки (Полис)"),

    INCORRECT_CODE("incorrect.code", "Неверный код"),

    NOT_AUTHORIZED("not.authorized", "Не авторизован"),

    YOU_ALREADY_IDENTIFIED("you.already.identified", "Вы уже Идентифицированы"),

    YOU_NOT_IDENTIFIED("you.not.identified", "Вы не прошли идентификацию"),
    YOUR_DOC_NOT_CHANGED("your.doc.not.changed", "Sizning passport ma'lumotlaringiz o'zgarmagan"),

    SMS_HAS_BEEN_SENT("sms.has.been.sent", "Был отправлен СМС на номер #NUMBER"),

    INSURANCE_OF_BANK_LOANS_INDIVIDUAL("insurance.of.bank.loans.individual", "Банк кредитларини суғурталаш (жисмоний шахс)"),

    CURRENT_BALANCE("current.balance", "Актуальный баланс"),

    USER_NOT_REGISTERED("user.not.registered", "user could not be identified"),
    USER_NOT_FOUND("user.not.found", "user could not found"),
    USER_COULD_NOT_BE_INDENTIFIED("user.could.not.be.indentified", "user could not be identified"),

    SCHEDULE_ENTITY_NOT_FOUND_WITH_ID("schedule.entity.not.found.with.ID", "ScheduleEntity Not Found withId: "),

    RESULT_IS_NULL("result.is.null", "Result is null"),

    PDF_FIELDS("pdf.fields", "PDF fields"),

    OPER_DAY_GET_ERROR("oper.day.get.error", "Oper day get error!"),

    INVALID_QR_CODE("invalid.qr.code", "Invalid QR code"),

    INTERNAL_SERVER_ERROR("internal.server.error", "Internal server error"),

    IMKON_INSURANCE("imkon.insurance", "IMKON.INSURANCE"),

    INSURANCE_NOT_FOUND("insurance.not.found", "insurance not found"),

    NO_ACTIVE_INSURANCES("no.active.insurances", "no active insurances"),

    EXCEPTION_MESSAGE("exception.message", "Exception message"),

    EPOS_OPERATION_NOT_FOUND("epos.operation.not.found", "Epos for operation. #OPERATIONCODE not found!!!"),

    COULD_NOT_SEND_REQUEST_TO_SCORING("could.not.send.request.to.scoring", "could not send request to scoring"),

    CHAT_DONT_WORK("chat.dont.work", "Chat don't work"),

    CAN_NOT_GET_HISTORY("can.not.get.history", "can not get history"),

    STATUS_IS_FULL("status.is.full", "Status is null"),

    PENSIONER_NOT_FOUND("pensioner.not.found", "Pensioner is not found"),

    DELETE_ACCOUNT_FORBIDDEN("delete.account.forbidden", "Удаление аккаунта запрещено"),

    IT_IS_FORBIDDEN_TO_ADD_CORPORATE_CARD("it.is.forbidden.to.add.corporate.card", "Запрещено добавлять корпоративную карту"),

    YOU_ARE_NOT_THE_NAMED_CARDHOLDER("you.are.not.the.named.cardholder", "Вы не являетесь именным владельцем карты"),

    CASHBACK_HISTORY_NOT_FOUND("cashback.history.not.found", "Вы не являетесь именным владельцем карты"),
    CASHBACK_PUSH_TITLE("cashback.push.title", "Tabriklaymiz! Siz xaznadan keshbek oldingiz"),
    CASHBACK_PUSH_BODY("cashback.push.body", "#AMOUNT UZS keshbek, Sizning onlayn hamyoningizga to'landi. Eng yuqori keshbeklar faqat bizda. xaznadan foydalanishni hamda keshbeklarni olishda davom eting."),

    P2P_PUSH_TITLE("p2p.push.title", "Pul o’tkazma qabul qilindi"),
    P2P_PUSH_BODY("p2p.push.body", "Sizning #MASKEDPAN kartangizga #AMOUNT UZS miqdorda pul o’tkazmasi #SENDERNAME dan qabul qilindi."),

    VIRTUAL_CARD_PUSH_BODY("virtual.card.push.body", "Tabriklaymiz arizangiz #ORDERID bo’yicha virtual karta #MASKEDPAN tayyor va Kartalar bo’limida ko’rsangiz bo’ladi. Savollaringiz bo’lsa bizga onlayn chat orqali murojaat qilsangiz bo’ladi."),
    VIRTUAL_CARD_PUSH_TITLE("virtual.card.push.title", "Yangi virtual karta uchun ariza #ORDERID"),

    WALLET_CREATE_PUSH_TITLE("wallet.create.push.title", "Yangi elektron hamyon uchun ariza #ORDERID"),
    WALLET_CREATE_PUSH_BODY("wallet.create.push.body", "Tabriklaymiz arizangiz #ORDERID bo’yicha elektron hamyon tayyor. Elektron hamyonlar bo’limida ko’rishingiz mumkin. Savollaringiz bo’lsa onlayn chat orqali murojaat qilishingiz mumkin."),

    DOC_UPDATED_PUSH_TITLE("doc.update.push.title", "Arizangiz ma'qullandi"),
    DOC_UPDATED_PUSH_BODY("doc.update.push.body", "#ORDERID - arizangiz bo'yicha passport ma'lumotlaringiz yangilandi"),

    MONEY_TRANSFER_PUSH_TITLE("money.transfer.push.title", "Hisob raqamga o'tkazma"),
    MONEY_TRANSFER_P2EA_PUSH_TITLE("money.transfer.push.title", "Hisob raqamga o'tkazma"),
    MONEY_TRANSFER_PUSH_BODY("money.transfer.push.body", "ID: #ORDERID sonli arizangiz bo'yicha amaliyot muvaffaqiyatli amalga oshirildi."),
    MONEY_TRANSFER_CHILD_PUSH_TITLE("money.transfer.child.push.title", "Оплата за детский сад."),
    MONEY_TRANSFER_STUDENT_PUSH_TITLE("money.transfer.student.push.title", "Оплата контракта (ВУЗа)"),
    MONEY_TRANSFER_CANCELLED_PUSH_BODY("money.transfer.cancelled.push.body", "ID: #ORDERID сонли аризангиз бўйича амалиёт бекор қилинди."),

    PAYMENT_MERCHANT_PUSH_BODY("payment.merchant.push.body", "#BUSINESSNAME uchun #AMOUNT so'm to'lovingiz muvaffaqiyatli amalga oshirildi"),
    PAYMENT_LOAN_TO_EDU_ACCOUNT("payment.loan.edu.account", "#AMOUNT so'm kredit to'lovi #UNIVERSITYNAMEga muvaffaqiyatli amalga oshirildi"),
    SMS_ACTIVATE_PUSH_BODY("sms.activate.push.body", "Sizning: #MASKEDPAN kartangizda sms xizmati muvaffaqqiyatli aktivlashdi."),

    INTERNATIONAL_MONEY_TRANSFER_PUSH_TITLE("international.money.transfer.push.title", "Xalqaro pul o'tkazmasi"),
    INTERNATIONAL_MONEY_TRANSFER_PUSH_BODY("international.money.transfer.push.body", "Siznining ID: #ORDERID raqamli o'tkazmangiz chet el valyutasidagi elektron hamyoningizga kirim qilindi. O'tkazmani \"Konversiya\" bo'limi orqali milliy valyutadagi bank kartangizga ayirboshlashingiz mumkin."),

    ERROR_WHILE_DECRYPTING("error.while.decrypting", "Ошибка при расшифровке"),
    ERROR_WHILE_ENCRYPTING("error.while.encrypting", "Ошибка при шифровании"),

    OPEN_DEPOSIT_PUSH_TITLE("open.deposit.push.title", "#DEPOSITNAME nomli omonat ochish"),
    OPEN_DEPOSIT_PUSH_BODY("open.deposit.push.body", "ID: #ORDERID sonli arizangiz bo'yicha amaliyot muvaffaqiyatli amalga oshirildi."),

    CLOSE_DEPOSIT_PUSH_TITLE("close.deposit.push.title", "Omonat hisobvarag'ini yopish"),
    CLOSE_DEPOSIT_PUSH_BODY("close.deposit.push.body", "Sizning #DEPOSITNAME nomli omonat hisobvarag'ingizdan #AMOUNT so'm mablag' hamyoningizga o'tkazildi"),

    INVESTING_DEPOSIT_PUSH_TITLE("investing.deposit.push.title", "Omonat hisobvarag'iga kirim qilish"),
    INVESTING_DEPOSIT_PUSH_BODY("investing.deposit.push.body", "Sizning #DEPOSITNAME nomli omonat hisobvarag'ingizga #AMOUNT so'm mablag' kirim qilindi"),

    WITHDRAW_DEPOSIT_PUSH_TITLE("withdraw.deposit.push.title", "Foizlarni yechib olish"),
    WITHDRAW_DEPOSIT_PUSH_BODY("withdraw.deposit.push.body", "Sizning #DEPOSITNAME nomli omonat hisobvarag'ingizdan #AMOUNT so'm mablag' hamyoningizga o'tkazildi"),

    PARTIAL_DECREASE_DEPOSIT_PUSH_TITLE("partial.decrease.deposit.push.title", "Qisman yechish"),
    PARTIAL_DECREASE_DEPOSIT_PUSH_BODY("partial.decrease.deposit.push.body", "Sizning #DEPOSITNAME nomli omonat hisobvarag'ingizdan #AMOUNT so'm mablag' hamyoningizga o'tkazildi"),

    INPS_CHECK_PUSH("loan.inps.check.push", "Уважаемый клиент, Ваша заявка на кредит была отклонена. Обновите информацию о ИНПС. Для получения дополнительной информации вы можете обратиться в службу онлайн-чата приложения или по короткому номеру 1106."),

    PRODUCT_NOT_SELECTED("product.not.selected", "product.not.selected"),
    AREA_NOT_FOUND("area.not.found", "area.not.found"),
    ORDERED_CARD_SUCCESSFULLY_SAVED("ordered.card.successfully.saved", "Buyurtmangiz muvaffaqiyatli saqlandi"),
    EXAM_PAYMENT_STATUS("exam.payment.status", "To'lanmagan"),
    REF_NUM_IS_ALREADY_PAYED("ref.num.already.payed", "Этот реферальный номер уже успешно оплачен"),

    EMAIL_FORMAT_IS_WRONG("email.format.is.wrong", "Формат электронной почты неверен"),
    EMAIL_NOT_FOUND("email.not.found", "Эмаил не найден"),
    EMAIL_CONFIRM_EXPIRED("email.confirm.expired", "Истек срок подтверждения электронной почты"),
    EMAIL_CONFIRM_CODE_INCORRECT("email.confirm.code.incorrect", "Неверный код подтверждения электронной почты"),
    EMAIL_CONFIRM_CODE_RETRY("email.confirm.code.retry", "Превышен лимит ввода кода подтверждения"),
    EMAIL_CONFIRM_ERROR("email.confirm.error", "Ошибка при подтверждения кода"),
    EMAIL_CONFIRM_SUCCESS("email.confirm.success", "Электронная почта успешно изменена"),
    EMAIL_IS_BLANK("email.is.blank", "Электронная почта пустой"),

    P2P_REQUEST_BODY("p2p.request.body", "#NAME запросил средства в размере #AMOUNT сум. \nОписание: #DESCRIPTION"),
    P2P_REQUEST_TITLE("p2p.request.title", "#NAME запросил средства в размере #AMOUNT сум."),
    P2P_REQUEST_SUCCESS("p2p.request.success", "#NAME запросил средства в размере #AMOUNT сум."),

    TRANSACTION_COUNT_LIMIT_EXCEEDED("transaction.count.limit.exceeded", "Вы достигли #PERIOD лимит"),
    TRANSACTION_AMOUNT_LIMIT_EXCEEDED("transaction.amount.limit.exceeded", "У вас остался #PERIOD лимит #AMOUNT сум"),
    TRANSACTION_MIN_AMOUNT("transaction.min.amount", ""),
    TRANSACTION_TEMPORARY_BLOCKED_FOR_DEVICE("transaction.temporary.blocked.for.device", "Осуществлен вход с нового устройства. В целях безопасности, просим повторить операцию через  несколько часов."),
    P2P_TEMPORARY_BLOCKED_FOR_NEW_CARD("p2p.temporary.blocked.for.new.card", "В целях соблюдения требований безопасности, для новодобавленных карт, доступ к Р2Р операциям открывается по истечении 1 часа."),
    P2P_TEMPORARY_BLOCKED_FOR_NEW_USER("p2p.temporary.blocked.for.new.user", "В целях соблюдения требований безопасности, для новорегистрируемых клиентов, доступ к Р2Р операциям открывается по истечении 1 часа."),

    HOURLY("hourly", "ежечасный"),
    DAILY("daily", "ежедневный"),
    WEEKLY("weekly", "еженедельный"),
    MONTHLY("monthly", "ежемесячный"),
    QUARTERLY("quarterly", "ежеквартальный"),
    YEARLY("yearly", "ежегодный"),

    HOUR("hour", "soat"),

    PRODUCT_NOT_FOUND("product.not.found", "product.not.found"),
    PRODUCT_AMOUNT("product.amount", "To'lov kontrakt miqdorida"),
    PHONE_NUMBER_IS_INCORRECT("phone.number.is.incorrect", "Номер телефона указан неверно"),
    USER_NOT_DELETED_CONTACT_OPERATOR("user.not.deleted.contact.operator", "userni o'chirib bo'lmadi iltimos operator bilan bog'laning"),
    ORDERED_CARD_NOT_FOUND("ordered.card.not.found", "ordered.card.not.found"),
    EXTERNAL_APPLICATION_SERVICE_ERROR("external.application.service.error", "Application error"),
    RECEIPT_EXISTS("receipt.exists.in.base", "Receipt exists"),
    RECEIPT_NOT_FOUND("receipt.not.found", "Receipt not found"),
    AVATAR_NOT_DELETED("avatar.not.deleted", "Изображение не было удалено"),
    AVATAR_DELETED("avatar.deleted", "Изображение удалено"),

    PAYMENT_NOT_FOUND("payment.not.found", "Оплата не найдена"),
    CAR_HAS_BEEN_ADDED_BEFORE("car.has.been.added.before", "Автомобиль был добавлен ранее"),
    BANK_CARD_ACTIVATION("bank.card.activation", "Все карты, подключенные к номеру телефона, привязаны к приложению."),
    CARD_IS_ALREADY_MAIN("card.already.main", "Karta allaqachon asosiy qilib belgilangan"),
    CARD_IS_NOT_VALID_FOR_MAIN("card.is.not.valid.for.main", "bu turdagi karta asosoy karta bo'la olmaydi"),
    ACTIVE_CARDS_LIMIT_REACHED("active_cards_limit_reached", "Вы достигли лимита максимального количества карт"),
    ACTIVE_CARDS_LIMIT_REACHED_FETCH("active_cards_limit_reached_fetch", "Вы достигли лимита максимального количества карт"),
    COURT_SUCCESS_RESPONSE("court.success.response", "Sudlanganlik yoki sudlanmaganlikni tekshish ximatidan muvaffaqiyatli javob olindi"),
    USER_FULL_NAME("user.full.name", "FIO"),
    USER_PASSPORT("user.passport", "Passport"),
    USER_PINFL("user.pinfl", "JSHSHIR"),
    REQUEST_TIME("request.time", "So'rov vaqti"),
    PINFL_NOT_EQUAL("pinfl.not.equal", "JSHSHIR mos emas"),
    MALE_USER("male.user", "Erkak"),
    FEMALE_USER("female.user", "Ayol"),
    DRIVER_LICENSE_NOT_FOUND("driver.license.not.found", "Haydovchilik guvohnomasi topilmadi"),
    DRIVER_INSURANCE_NOT_FOUND("driver.insurance.not.found", "Sug'urta topilmadi"),
    CALL_TO_OPERATOR("call.to.operator", "something went wrong, please call to operator"),
    DOC_UPDATE_ERROR_CALL_TO_OPERATOR("doc.update.error.call.to.operator", "Hujjatingizni oldik. Arizangizni Mening murojatlarim bo'limida kuzatishingiz mumkin. Qayta ishlashni tugatganimizdan keyin sizga xabar beriladi."),
    PAYED_STATUS("payed.status", "To'langan"),
    INPS_NOT_EXIST("inps.not.found", "Inps topilmadi"),
    INPS_INTERNAL_CONTROL_ERROR("inps.internal.control.error", "Amaliyotni bajarishda xatolik - Taqiqlangan operatsiya \"#N\" ro‘yxatdagi shaxs bilan operatsiya bajarilmoqda. Operatsiyani amalga oshirish uchun chat orqali murojaat qoldiring yoki qisqa raqam 1106 ga telefon qiling."),
    YOU_ARE_NOT_PENSIONER("you.are.not.pensioner", "Siz nafaqa oluvchi emassiz"),
    DEPOSIT_FUNCTION_FORBIDDEN("deposit.is.not.active", "Данная функция не доступно. Для получения дополнительной информации вы можете обратиться в службу онлайн-чата приложения или по короткому номеру 1106."),
    NOT_PAYED_STATUS("not.payed.status", "To'lanmagan"),
    INVALID_LOAN_AMOUNT("invalid.loan.amount", "invalid loan amount"),
    CREATE_CUSTOMER_ERROR("oper.customer.error", "Create customer error!"),
    USER_LOAN_APPLICATION_ERROR("user.loan.application.error", "Afsuski, hozirda siz ushbu kredit mahsulotidan foydalana olmaysiz. Sizning ish beruvchingiz Xalq Bankning ish haqi loyihasining ishtirokchisi bo'lishi kerak. Yangi kredit mahsulotlari tez orada ariza topshirishingiz mumkin bo'ladi."),
    LOAN_SUCCESS_MESSAGE("loan.success.message", "Sizning arizangiz ko'rib chiqish uchun qabul qilindi. Ariza ID #ORDERID. Mening kreditlarim va Mening murojatlarim bo'limlarida arizaning holatini kuzatib boring."),
    LOAN_SUCCESS_ACCEPTED_MESSAGE("loan.success.accepted.message", "Kredit summa qabul qilindi. Mening kreditlarim bo'limida arizaning holatini kuzatib boring."),

    USER_LOAN_APPLICATION_STEP_ERROR("user.loan.application.step.error", "User loan application is in process!"),
    USER_LOAN_APPLICATION_STEP_SCORING_ERROR("user.loan.application.step.scoring.error", "User loan application can not pass scoring!"),
    USER_LOAN_APPLICATION_INSURANCE_ERROR("user.loan.application.insurance.error", "User already has insurance!"),
    LOAN_INSURANCE_PAYMENT_ACCEPTED("loan.insurance.payment.accepted", "Hurmatli mijoz, Kredit uchun Sug'urta polisini oldingiz. Kreditingizga aloqador sug'urta polisini ilovaning \"Kvitansiyalar\" bo'limidan yuklab olishingiz mumkin."),
    MY_AUTO_NOT_FOUNT("my.auto.not.fount", "Avtomobil topilmadi!"),
    MY_AUTO_OIL_NOT_FOUNT("my.auto.oil.not.fount", "Avtomobil moy almashtirish muddati topilmadi!"),
    MY_AUTO_TINTING_NOT_FOUNT("my.auto.tinting.not.fount", "Avtomobil oynalarini qoraytirish muddati topilmadi!"),
    MY_AUTO_PROXY_NOT_FOUNT("my.auto.proxy.not.fount", "Ishonchnoma topilmadi!"),
    MY_AUTO_GAS_NOT_FOUNT("my.auto.gas.not.fount", "Avtomobil gaz ma'lumotlari topilmadi!"),
    MY_AUTO_INSURANCE_NOT_FOUNT("my.auto.insurance.not.fount", "Sug'urta ma'lumotlari topilmadi!"),
    MY_AUTO_TEXPASSPORT_NOT_EQUAL("my.auto.texpassport.not.equal", "Avtomabil raqami va texpasport mos emas"),
    AUTO_ATTORNEY_PERIOD_ONE_MONTH("auto.attorney.1.month", "1 месяц"),
    AUTO_ATTORNEY_PERIOD_SIX_MONTH("auto.attorney.6.month", "6 месяц"),
    AUTO_ATTORNEY_PERIOD_THREE_YEAR("auto.attorney.3.year", "3 год"),
    STATE_SERVICE_NOT_FOUND("state.service.not.found", "Xizmat ma'lumotlari topilmadi"),
    USER_BIRTHDAY("user.birthday", "Tug‘ilgan sanasi"),

    //    user debt
    USER_DEBT_NOT_FOUND("user.debt.not.found", "Qarz topilmadi"),
    USER_DEBT_ASK_TITLE("user.debt.ask.title", "Qarz so'rash"),
    USER_DEBT_ASK("user.debt.ask", "#FIO #DATE muddatgacha #AMOUNT UZS miqdorida qarz so'ramoqda! \nIzoh: #DESCRIPTION"),
    DEBT_WARNING_TITLE("debt.warning.title", "Qarzingizni qaytarishni unutmang!"),
    DEBT_WARNING_BODY("debt.warning.body", "#FIOga #DATE muddatgacha #AMOUNT UZS miqdorida mablag'ni qaytarishni unutmang."),
    DEBT_SUCCESSFULLY_ISSUED("debt.successfully.issued", "#FIO #AMOUNT UZS miqdordagi qarz so'rovinggizni qabul qildi va #GIVEN_AMOUNT UZS miqdorda qarz berdi"),
    DEBTOR_USER_NOT_FOUND("debtor.user.not.found", "Qarzdor topilmadi!"),
    INVALID_DAY("invalid.day", "Дата неверна!"),
    NO_LENDER_FOUND("no.lender.found", "Qarz beruvchi topilmadi!"),
    NOT_TO_LEND("not.to.lend", "#FIO #AMOUNT UZS miqdordagi qarz so'rovinggizni rad etdi \nIzoh: #DESCRIPTION"),
    DEBT_REMINDER_TITLE("debt.reminder.title", "Eslatma"),
    DEBT_PAY_REMINDER("debt.pay.reminder", "#FIO #DATE sanasida #AMOUNT UZS miqdorida qarzini qaytarishi kerak"),
    DEBT_PAID_TITLE("debt.paid.title", "Berilgan qarz qaytarildi"),
    DEBT_PAID("debt.paid", "#FIO #DATE da #AMOUNT UZS miqdorida so'ralgan qarzni qaytardi"),
    DEBT_PAID_FOR_DEBTOR("debt.paid.for.debtor", "#FIO dan #DATE da #AMOUNT UZS miqdorida so'ralgan qarzinggizni qaytarganinggiz bilan tabriklaymiz"),

    PENSIONER_REGION("pensioner.region", "Регион"),
    PENSIONER_MAHALLA("pensioner.mahalla", "Махаллю"),
    PENSIONER_GRAPHICS("pensioner.graphics", "Даты (каждого месяца)"),
    PENSIONER_AREA("pensioner.area", "Район"),
    PENSIONER_GRAPHIC_EXIST("pensioner.graphic.exist", "Вы создали данные до"),
    USER_DOC_EXPIRED("user.doc.expired", "Your passport is expired! Please update your profile."),

    TRANSFER_FROM_CARD_TO_CARD("transfer.from.card.to.card", "перевод с карты на карту"),
    CARD_REPLENISHMENT("card.replenishment", "пополнение карты"),
    PAYMENT_FOR_PRODUCTS_AND_SERVICES("payment.for.products.and.services", "оплата товаров и услуг"),
    P2P_TRANSFER("p2p.transfer", "p2p перевод"),
    INCOMING_TRANSFER("incoming.transfer", "входящий перевод"),
    CANCELLATION_OF_PAYMENT_FOR_PRODUCTS_AND_SERVICES("cancellation.payment.for.products.and.services", "отмена оплаты товаров и услуг"),
    CANCELLATION_OF_CASH_WITHDRAWAL("cancellation.cash.withdrawal", "отмена снятия наличных"),
    CANCELLATION_OF_REFUNDS("cancellation.refunds", "возврат средств за отмену"),
    CANCELING_AN_INCOMING_TRANSFER("canceling.incoming.transfer", "отмена входящего перевода"),
    BALANCE_CHECK("balance.check", "проверка баланса"),
    ACCOUNT_MAINTENANCE_FEE("account.maintenance.fee", "комиссия за обслуживание счета"),
    CASH_WITHDRAWAL("cash.withdrawal", "выдача наличных"),
    CARD_DEBITING("card.debiting", "списание с карты"),
    CANCELLATION_OF_REPLENISHMENT("cancellation.replenishment", "отмена пополнения"),
    CANCELLATION_OF_DEBIT("cancellation.debit", "дебет за аннулирование"),
    DEFAULT_TRANSACTION_TYPE("default.transaction.type", "тип транзакции по умолчанию"),
    MOBILE_PHONE_PAYMENT("mobile.phone.payment", "оплата мобильного телефона"),
    FAST_CASH("fast.cash", "быстрые деньги"),
    SECOND_PART_OF_TWO_STEPS_POS_CREDIT_TRANSACTION("second.part.of.two.steps.pos.credit.transaction", "вторая часть двухшаговой POS-кредитной сделки"),
    P2P_CREDIT("p2p.credit", "поступления"),
    P2P_DEBIT("p2p.debit", "расходы"),
    PURCHASE_FROM_POS("purchase.from.pos", "покупка в магазине"),
    FEE_DISBURSEMENT("fee.disbursement", "выплата комиссии"),
    FEE_COLLECTION("fee.collection", "сбор пошлин"),
    REVERSAL_PRESENTMENT("reversal.presentment", "перевернутое представление"),
    REVERSAL_CHARGE_BACK("reversal.charge.back", "возврат платежа"),
    CHARGE_BACK("charge.back", "вернуть деньги"),
    REVERSAL_CASH_WITHDRAWAL("reversal.cash.withdrawal", "возврат наличных денег"),
    CARD_TO_CARD("card.to.card", "карта на карту"),
    CURRENCY_EXCHANGE("currency.exchange", "обмен валюты"),
    CURRENCY_NOT_SUPPORTED("currency.not.supported", "Тип валюты не поддерживается"),
    FULL_ADVANCED_REPAYMENT("full.advanced.repayment", "полное досрочное погашение"),
    CASH_WITHDRAWAL_BY_VIRTUAL_CARD("cash.withdrawal.by.virtual.card", "снятие наличных на виртуальную карту"),
    DIRECT_DEBIT_CREDIT_REPAYMENT("direct.debit.credit.repayment", "погашение кредита прямым дебетом"),
    DIRECT_DEBIT_FEE_REPAYMENT("direct.debit.fee.repayment", "погашение комиссии за прямой дебет"),
    EPOS_PURCHASE("epos.purchase", "расходы"),
    UTILITY_PAYMENT("utility.payment", "универсальный платеж"),
    EPOSC_CASH_ADVANCE("eposc.cash.advance", "выдача наличных"),
    UNDEFINED("undefined", "неопределенный"),

    // device
    DEVICE_IDENTIFICATION_SUCCESS("device.identification.success", "Устройство подтверждена"),
    DEVICE_IDENTIFICATION_ERROR("device.identification.error", "Устройство неподтверждена"),
    DEVICE_NOT_FOUND("device.not.found", "Устройство не найдено"),
    DEVICE_CHECK_UPDATE_TIME("device.check.update.time", "Hurmatli mijoz, Sizning qurilmangiz oxirgi yangilangan vaqti yaqin bo'lganligi sababli bu amaliyotni bajara olmaysiz. Iltimos keyinroq urinib ko'rsangiz."),

    // promo code
    PROMO_CODE_ACTIVATED("promo.code.activated", "Congratulations! PromoCode successfully activated!"),
    PROMO_CODE_ALREADY_ACTIVATED("promo.code.already.activated", "PromoCode is already activated!"),
    PROMO_CODE_NOT_FOUND("promo.code.not.found", "Promo Code does not exist!"),

    INCORRECT_PASSWORD_FORMAT("password.format.not.valid", "password.format.not.valid"),
    SESSION_NOT_FOUND("session.not.found", "Session does not exist!"),
    PARAM_NOT_FOUND("param.not.found", "Param not found");

    private final String key;
    private final String value;


}
